version: '3.8'

services:
  mysql-meta:
    image: mysql:8.0
    container_name: mysql-meta
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: batch_mata
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ~/docker-volumes/spring-batch/mysql-meta:/var/lib/mysql
    networks:
      - batch-network

  mysql-data:
    image: mysql:8.0
    container_name: mysql-data
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: batch_data
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ~/docker-volumes/spring-batch/mysql-data:/var/lib/mysql
    networks:
      - batch-network

networks:
  batch-network:
    driver: bridge